### ISSUE TITLE
Seminar feedback

### ISSUE THREAD

**Issue by cwehmeyer** [markovmodel/pyemma_tutorials#100]
Here is the collected feedback on **notebooks** from the group seminar:

## 00 pipeline

- [x] ~~citations for methods, when we introduce them~~ (will be handled via #105)
- [ ] state, that vamp/tica/(msm?) lag time is a modelers choice.
- [x] compute validated score (do not use the training score) - test/train set splitting
- [x] log scale on feature histograms for better visualization of tiny features.

- [x] Catch warnings (div by zeros) - does not look too fancy.
- [x] ipymol (pymol server frontend)? (optional)
- [x] maybe provide structures for metastable states etc. as PDB for people familiar with molecular viewers.
- [x] use secondary structure for visualizing the metastable states. Is it possible to use 4 separate views?
- [x] ~~sort metastable sets by π~~
- [x] ~~show uncertainties for mfpts~~  (#97)
- [ ] show probability flux or mftps between two sets (eg. unfolding process) on the coarse grained network.
- [x] try to make things more robust/reproducible, i.e.,
    - ~~do not use indexes of metastable sets, because these can flip, but do it on a observable.~~ (#97)
   -  ~~fixed seed for kmeans~~ (#97) 
- [x] ~~mention randomness of kmeans (wrap up and when introducing it)~~ (#97)

## 01 io/feat

- [x] vamp scores should be validated (or at least mentioned, that it should be done - it is done in nb 02)

## 06 hmm

- [x] its for longer lag times is too expensive, but it would be nice to show it...

## 08 common problems

- [x] limit nits in cell 22

**Comment by thempel** [comment]
The 00 section is partially a duplicate of #97 which I've started fixing yesterday. Some of those points are already done, cf. this branch: https://github.com/markovmodel/pyemma_tutorials/tree/rev00

**Comment by thempel** [comment]
Please correct me if I'm wrong, but I got the impression that we will stick to a slightly improved NGLView representation since everything else is probably unfeasible in the notebooks. Instead, we make clear how to export files to view them in VMD or PyMOL. After all, its not a tutorial for MD visualization tools. I'll close those points above.
